version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - path: ".env"
    environment:
      MYSQL_HOST: $DB_HOST
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  php:
    container_name: php
    depends_on:
      mysql:
        condition: service_healthy
    image: jericho-penugasan-3-php
    build:
      target: php
      context: .
    networks:
      - laravel-net
    restart: on-failure
    ports:
      - "5173:5173"
    volumes:
      - app:/var/www/html

  migration:
    image: jericho-penugasan-3-php
    container_name: migration
    command: php artisan migrate:fresh --seed
    depends_on:
      php:
        condition: service_started
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - laravel-net
    volumes:
      - app:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app:/var/www/html
    networks:
      - laravel-net
    depends_on:
      - php
    restart: on-failure

volumes:
  app:

networks:
  laravel-net:
    driver: bridge