version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: pbkk
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-net

  php:
    container_name: php
    depends_on:
      - mysql
    image: jjch0nc/jericho-penugasan-3
    networks:
      - laravel-net
    restart: on-failure
    volumes:
      - app:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app:/var/www/html
    networks:
      - laravel-net
    depends_on:
      - mysql
      - php
    restart: on-failure

volumes:
  app:

networks:
  laravel-net:
    driver: bridge