version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: pbkk
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  php:
    container_name: php
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    image: jjch0nc/jericho-penugasan-3
    networks:
      - laravel-net
    restart: on-failure
    volumes:
      - app:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app:/var/www/html
    networks:
      - laravel-net
    depends_on:
      - php
    restart: on-failure

volumes:
  app:

networks:
  laravel-net:
    driver: bridge