version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - path: ".env"
    environment:
      MYSQL_HOST: $DB_HOST
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  php:
    container_name: php
    env_file:
      - path: ".env"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    build:
      target: php
      context: .
    networks:
      - laravel-net
    restart: on-failure
    ports:
      - "5173:5173"

  migration:
    image: tamiyochi-laravel-php
    env_file:
      - path: ".env"
    container_name: migration
    command: php artisan migrate:fresh --seed
    depends_on:
      nginx:
        condition: service_healthy
    restart: on-failure
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure

networks:
  laravel-net:
    driver: bridge