name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jericho-penugasan-3:latest
          cache-from: type=gha,scope=build
          cache-to: type=gha,scope=build,mode=max
      
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Copy docker-compose.yml to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "./docker-compose.yml"
        target: "."
        strip_components: 1
    -
      name: executing remote ssh commands using private key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jericho-penugasan-3:latest
          docker compose down
          docker compose up -d
          docker run -it --name php ${{ secrets.DOCKERHUB_USERNAME }}/jericho-penugasan-3:latest /bin/sh -c "sh installer.sh"
